trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  - group: AzureSubscriptionInfo

steps:
- task: Docker@0
  displayName: 'Build an image'
  inputs:
    azureSubscription: '$(azureSubscription)'
    azureContainerRegistry: '$(azureRegistry)'
    dockerFile: app/CustomerApp/Dockerfile
    defaultContext: false
    context: app
    imageName: 'customer-app:$(Build.BuildNumber)'

- task: Docker@0
  displayName: 'Push an image'
  inputs:
    azureSubscription: '$(azureSubscription)'
    azureContainerRegistry: '$(azureRegistry)'
    action: 'Push an image'
    imageName: 'customer-app:$(Build.BuildNumber)'

- task: CopyFiles@2
  displayName: 'Copy migrations to the drop folder'
  inputs:
    SourceFolder: 'sql'
    Contents: '**'
    TargetFolder: 'infrastructure'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: infrastructure
