trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@0
  displayName: 'Build an image'
  inputs:
    azureSubscription: 'Windows Azure MSDN - Visual Studio Ultimate (8326d01c-4f7e-47d6-b58f-8d4596245ec1)'
    azureContainerRegistry: '{"loginServer":"customerappacr00.azurecr.io", "id" : "/subscriptions/8326d01c-4f7e-47d6-b58f-8d4596245ec1/resourceGroups/customer-app/providers/Microsoft.ContainerRegistry/registries/customerappacr00"}'
    dockerFile: app/CustomerApp/Dockerfile
    defaultContext: false
    context: app
    imageName: 'customer-app:$(Build.BuildNumber)'

- task: Docker@0
  displayName: 'Push an image'
  inputs:
    azureSubscription: 'Windows Azure MSDN - Visual Studio Ultimate (8326d01c-4f7e-47d6-b58f-8d4596245ec1)'
    azureContainerRegistry: '{"loginServer":"customerappacr00.azurecr.io", "id" : "/subscriptions/8326d01c-4f7e-47d6-b58f-8d4596245ec1/resourceGroups/customer-app/providers/Microsoft.ContainerRegistry/registries/customerappacr00"}'
    action: 'Push an image'
    imageName: 'customer-app:$(Build.BuildNumber)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: infrastructure


