apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-app
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: customer-app
    spec:
      containers:
      - name: customer-app
        image: {{acr_url}}/customer-app
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
          name: customer-app-config
---
apiVersion: v1
kind: Service
metadata:
  name: customer-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
app: customer-app