apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-app
  labels:
    app: customer-app
spec:
  selector:
    matchLabels:
      app: customer-app
  replicas: 3
  template:
    metadata:
      labels:
        app: customer-app
    spec:
      containers:
      - name: customer-app
        image: _{image_name}_
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
        ports:
        - containerPort: 80
        env:
        - name: SQLAZURECONNSTR_CustomerDb
          value: "_{connection-string}_"
---
apiVersion: v1
kind: Service
metadata:
  name: customer-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: customer-app